import { readFile, writeFile } from "node:fs/promises";

const file = new URL("../src/ui/i18n/opencaddie_nb.ts", import.meta.url);
const translations = {
  "My bag": "Min bag",
  "Carry distances drive on-course recommendations": "Slaglengdene brukes til kølleanbefalinger",
  "Enabled clubs": "Aktive køller",
  "Stored canonically in metres": "Lagres alltid i meter",
  "Move up": "Flytt opp",
  "Move down": "Flytt ned",
  "Edit club": "Rediger kølle",
  "Add club": "Legg til kølle",
  "Club name": "Køllenavn",
  "Example: 7 iron": "Eksempel: 7-jern",
  "Carry (metres)": "Slaglengde (meter)",
  "Carry (yards)": "Slaglengde (yards)",
  "Use for recommendations": "Bruk i anbefalinger",
  "Save": "Lagre",
  "Add": "Legg til",
  "New": "Ny",
  "Remove": "Fjern",
  "Remove club?": "Fjerne køllen?",
  "The club will no longer be available for recommendations.": "Køllen blir ikke lenger brukt i anbefalinger.",
  "Previous": "Forrige",
  "Scorecard": "Scorekort",
  "Finish": "Fullfør",
  "Next": "Neste",
  "Cancel": "Avbryt",
  "Confirm": "Bekreft",
  "Courses": "Baner",
  "Downloaded courses work without internet": "Nedlastede baner fungerer uten internett",
  "Offline library": "Frakoblet bibliotek",
  "%1 courses": "%1 baner",
  "Offline · %1% quality · © OSM (ODbL)": "Frakoblet · %1 % kvalitet · © OSM (ODbL)",
  "Set up round": "Sett opp runde",
  "Find a course": "Finn en bane",
  "OpenGolfMap service": "OpenGolfMap-tjeneste",
  "Connect to Wi-Fi to search": "Koble til Wi-Fi for å søke",
  "Course name or place": "Bane eller sted",
  "Searching…": "Søker …",
  "Search": "Søk",
  "Download": "Last ned",
  "Wi-Fi settings": "Wi-Fi-innstillinger",
  "Downloading %1%": "Laster ned %1 %",
  "Remove offline course?": "Fjerne frakoblet bane?",
  "The course can be downloaded again later. Round history is kept.": "Banen kan lastes ned igjen senere. Rundehistorikken beholdes.",
  "Round history": "Rundehistorikk",
  "Search, inspect, resume, and export": "Søk, se detaljer, fortsett og eksporter",
  "Rounds": "Runder",
  "Search course": "Søk etter bane",
  "Select a round": "Velg en runde",
  "Score and statistics": "Score og statistikk",
  "Hole": "Hull",
  "Par": "Par",
  "Score": "Score",
  "Putts": "Putter",
  "Pen.": "Straff",
  "Fairway": "Fairway",
  "Delete": "Slett",
  "Delete round?": "Slette runden?",
  "This permanently removes the local scorecard and statistics.": "Dette sletter det lokale scorekortet og statistikken permanent.",
  "Hole %1": "Hull %1",
  "Par %1    Index %2": "Par %1    Indeks %2",
  "Front": "Forkant",
  "Centre": "Senter",
  "Back": "Tilbake",
  "Back edge": "Bakkant",
  "Recommended: %1": "Anbefalt: %1",
  "Club advice unavailable": "Kølleanbefaling utilgjengelig",
  "%1 from target carry": "%1 fra ønsket slaglengde",
  "Needs a fresh GPS fix within 25 m accuracy": "Krever en fersk GPS-posisjon med maks. 25 m nøyaktighet",
  "%1 strokes": "%1 slag",
  "Stats": "Statistikk",
  "Plays like — unavailable": "Spiller som — utilgjengelig",
  " ±%1 m": " ±%1 m",
  "Hole %1 details": "Detaljer for hull %1",
  "Close": "Lukk",
  "Penalties": "Straffeslag",
  "Left": "Venstre",
  "Right": "Høyre",
  "Missed": "Bom",
  "Green in regulation": "Green på regulært antall slag",
  "Notes": "Notater",
  "Optional round note": "Valgfritt rundenotat",
  "Save and close": "Lagre og lukk",
  "Space": "Mellomrom",
  "Done": "Ferdig",
  "Round format": "Rundeformat",
  "Holes": "Hull",
  "9 holes": "9 hull",
  "18 holes": "18 hull",
  "Scoring": "Spilleform",
  "Stroke play": "Slagspill",
  "Stableford": "Stableford",
  "Player and tee": "Spiller og utslag",
  "Course handicap": "Banehandicap",
  "Tee": "Utslagssted",
  "Yellow": "Gul",
  "This round and course remain available without internet.": "Runden og banen forblir tilgjengelige uten internett.",
  "Start round": "Start runde",
  "Gross %1": "Brutto %1",
  "E": "E",
  "%1 pts": "%1 poeng",
  "Index": "Indeks",
  "Strokes": "Slag",
  "Points": "Poeng",
  "Back to hole": "Tilbake til hull",
  "Abandon": "Avbryt runde",
  "Finish round": "Fullfør runde",
  "Abandon round?": "Avbryte runden?",
  "The partial scorecard stays in history as abandoned.": "Det ufullstendige scorekortet lagres som avbrutt i historikken.",
  "Finish round?": "Fullføre runden?",
  "The scorecard will be saved to round history.": "Scorekortet lagres i rundehistorikken.",
  "Settings": "Innstillinger",
  "Display, scoring, map, connectivity, and privacy": "Skjerm, score, kart, tilkobling og personvern",
  "Display": "Skjerm",
  "Dark": "Mørk",
  "Light": "Lys",
  "Metric": "Metrisk",
  "Imperial": "Imperial",
  "Text size": "Tekststørrelse",
  "Brightness": "Lysstyrke",
  "Round behavior": "Rundeinnstillinger",
  "Advanced score fields": "Utvidede scorefelt",
  "Automatic hole advance": "Automatisk hullbytte",
  "Club advice bias": "Justering av kølleråd",
  "Map colors": "Kartfarger",
  "Tap a swatch to cycle accessible presets": "Trykk på en farge for å bytte mellom tydelige valg",
  "Green": "Green",
  "Water": "Vann",
  "Sand": "Sand",
  "Rough": "Rough",
  "Wood": "Skog",
  "Path": "Sti",
  "Connectivity and diagnostics": "Tilkobling og diagnostikk",
  "GPS: %1": "GPS: %1",
  "Internet available": "Internett tilgjengelig",
  "Offline": "Frakoblet",
  "Course cache": "Banelagring",
  "Privacy-safe diagnostic logging": "Personvernvennlig diagnostikklogg",
  "Reset settings": "Nullstill innstillinger",
  "Reset settings?": "Nullstille innstillingene?",
  "Round history, clubs, and downloaded courses are kept.": "Rundehistorikk, køller og nedlastede baner beholdes.",
  "Back": "Tilbake",
  "Offline-first golf computer": "Golfcomputer laget for frakoblet bruk",
  "%1% battery": "%1 % batteri",
  "External power": "Ekstern strøm",
  "Round in progress": "Runde pågår",
  "%1 · Hole %2 of %3": "%1 · Hull %2 av %3",
  "Resume": "Fortsett",
  "Resume round": "Fortsett runden",
  "Play golf": "Spill golf",
  "History": "Historikk",
  "Wi-Fi": "Wi-Fi",
  "My clubs": "Mine køller",
  "Club": "Kølle",
  "Club advice": "Kølleanbefaling",
  "%1 from target": "%1 fra målet",
  "Needs fresh GPS": "Krever fersk GPS",
  "Connected to %1": "Tilkoblet %1",
  "Not connected": "Ikke tilkoblet",
  "Scanning…": "Søker …",
  "Scan": "Søk",
  "Available networks": "Tilgjengelige nettverk",
  "Connect": "Koble til",
  "Network name": "Nettverksnavn",
  "Password": "Passord",
  "Hidden network": "Skjult nettverk",
  "Forget": "Glem",
  "OpenCaddie supports personal WPA2/WPA3. Enterprise Wi-Fi is outside V1.": "OpenCaddie støtter personlig WPA2/WPA3. Bedrifts-Wi-Fi er ikke med i V1.",
  "Password is required.": "Passord er påkrevd.",
  "Network forgotten.": "Nettverket er glemt.",
  "No Wi-Fi adapter was found.": "Fant ingen Wi-Fi-adapter.",
  "The selected network is unavailable.": "Det valgte nettverket er utilgjengelig.",
  "Could not connect to the network.": "Kunne ikke koble til nettverket.",
  "Could not list saved networks.": "Kunne ikke vise lagrede nettverk.",
  "Saved network was not found.": "Fant ikke det lagrede nettverket.",
  "Simulator course fixture is missing.": "Simulatorens testbane mangler.",
  "Course search failed: %1": "Banesøket mislyktes: %1",
  "The course service returned invalid data.": "Banetjenesten returnerte ugyldige data.",
  "Course import failed: %1": "Baneimporten mislyktes: %1",
  "The course service did not return a course ID.": "Banetjenesten returnerte ingen bane-ID.",
  "Course download failed: %1": "Nedlasting av banen mislyktes: %1",
  "The course service returned the wrong file type.": "Banetjenesten returnerte feil filtype.",
  "Could not read simulator GPS route.": "Kunne ikke lese simulatorens GPS-rute.",
  "Course cache limit reached. Remove a course or increase the limit in Settings.": "Lagringsgrensen er nådd. Fjern en bane eller øk grensen i Innstillinger.",
  "%1 is ready offline.": "%1 er klar for frakoblet bruk.",
  "OpenCaddie Demo Course": "OpenCaddie-demobane",
  "Bundled": "Inkludert",
  "m": "m",
  "yd": "yd",
  "Offline course removed.": "Den frakoblede banen er fjernet.",
  "Finish or abandon the active round first.": "Fullfør eller avbryt den aktive runden først.",
  "The selected course is not available offline.": "Den valgte banen er ikke tilgjengelig frakoblet.",
  "Stableford needs valid par and stroke index for every hole.": "Stableford krever gyldig par og indeks for hvert hull.",
  "Correct missing par/index data before using Stableford.": "Korriger manglende par-/indeksdata før Stableford brukes.",
  "Could not start the round.": "Kunne ikke starte runden.",
  "Could not abandon the round.": "Kunne ikke avbryte runden.",
  "Could not finish the round.": "Kunne ikke fullføre runden.",
  "Round saved.": "Runden er lagret.",
  "Could not add the club.": "Kunne ikke legge til køllen.",
  "Could not update the club.": "Kunne ikke oppdatere køllen.",
  "Could not remove the club.": "Kunne ikke fjerne køllen.",
  "Could not reorder clubs.": "Kunne ikke endre rekkefølgen på køllene.",
  "Exported to %1": "Eksportert til %1",
  "Use HTTPS (HTTP is allowed for localhost only).": "Bruk HTTPS (HTTP er kun tillatt for localhost).",
  "Could not reset settings.": "Kunne ikke nullstille innstillingene.",
  "Settings reset.": "Innstillingene er nullstilt.",
  "%1 m": "%1 m",
  "%1 yd": "%1 yd",
  "Waiting for GPS": "Venter på GPS",
  "Low accuracy": "Lav nøyaktighet",
  "Stale GPS fix": "Utdatert GPS-posisjon",
  "GPS ready": "GPS klar",
  "%1%2 %3": "%1%2 %3",
  "Score could not be saved.": "Scoren kunne ikke lagres.",
  "Setting could not be saved.": "Innstillingen kunne ikke lagres.",
  "Could not open the course render model.": "Kunne ikke åpne banens rendermodell.",
  "The course has no renderable holes.": "Banen har ingen hull som kan vises.",
  "Could not render the course geometry.": "Kunne ikke tegne banens geometri.",
  "JSON": "JSON",
  "CSV": "CSV"
};

const escapeXml = (value) => value
  .replaceAll("&", "&amp;").replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;").replaceAll("\"", "&quot;");
const unescapeXml = (value) => value
  .replaceAll("&quot;", "\"").replaceAll("&gt;", ">")
  .replaceAll("&lt;", "<").replaceAll("&amp;", "&");

let xml = await readFile(file, "utf8");
const missing = new Set();
xml = xml.replace(
  /<source>([\s\S]*?)<\/source>\s*<translation\b[^>]*>[\s\S]*?<\/translation>/g,
  (whole, encodedSource) => {
    const source = unescapeXml(encodedSource);
    const translated = translations[source];
    if (translated === undefined) missing.add(source);
    return `<source>${encodedSource}</source>\n        <translation>${escapeXml(translated ?? source)}</translation>`;
  }
);
await writeFile(file, xml);
if (missing.size) {
  console.warn(`Using source text for ${missing.size} untranslated strings:`);
  console.warn([...missing].sort().join("\n"));
}
